// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtdVkMP_YUm9d2ulInXiQD36XmJMkJOfs',
    appId: '1:1055085684931:web:b5f786c0373e0f3cc21a76',
    messagingSenderId: '1055085684931',
    projectId: 'evently-2c40b',
    authDomain: 'evently-2c40b.firebaseapp.com',
    storageBucket: 'evently-2c40b.firebasestorage.app',
    measurementId: 'G-GFLQD3Z15B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkVL-9-e-KM3nEDNo9kKHWzTeJ1rDiFtg',
    appId: '1:1055085684931:android:7c30210d11c75147c21a76',
    messagingSenderId: '1055085684931',
    projectId: 'evently-2c40b',
    storageBucket: 'evently-2c40b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2c8vpJBMAyb0Bot551gCEXlAMrD-bS8',
    appId: '1:1055085684931:ios:13e4f17c4cd83c27c21a76',
    messagingSenderId: '1055085684931',
    projectId: 'evently-2c40b',
    storageBucket: 'evently-2c40b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2c8vpJBMAyb0Bot551gCEXlAMrD-bS8',
    appId: '1:1055085684931:ios:13e4f17c4cd83c27c21a76',
    messagingSenderId: '1055085684931',
    projectId: 'evently-2c40b',
    storageBucket: 'evently-2c40b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtdVkMP_YUm9d2ulInXiQD36XmJMkJOfs',
    appId: '1:1055085684931:web:9f5a39104806b447c21a76',
    messagingSenderId: '1055085684931',
    projectId: 'evently-2c40b',
    authDomain: 'evently-2c40b.firebaseapp.com',
    storageBucket: 'evently-2c40b.firebasestorage.app',
    measurementId: 'G-VY86ZST0T8',
  );
}
